image: node:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd frontend
    - yarn install

deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - yarn deploy
