image: node:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd frontend
    - yarn install
    - pip3 install awscli
    - yarn build
    - yarn test
    - yarn deploy
