image: node:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - frontend/node_modules/

build:
  stage: build
  script:
    - pwd
    - cd frontend
    - yarn install
    - yarn build

test:
  stage: test
  script:
    - pwd
    - cd frontend
    - yarn test

deploy:
  stage: deploy
  image: python:latest
  script:
    - pwd
    - pip install awscli
    - cd frontend
    - cd build
    - aws s3 cp --recursive /build s3://ipa-flashcards-app-frontend

