image: node:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - frontend/node_modules/

build:
  stage: build
  only:
    - merge_requests
  script:
    - cd frontend
    - yarn install
    - yarn build
  artifacts:
    paths:
      - frontend/build
    expire_in: 1 hour

test:
  stage: test
  script:
    - cd frontend
    - yarn test

deploy:
  stage: deploy
  image: python:latest
  only:
    - merge_requests
  script:
    - pip install awscli
    - cd frontend
    - aws s3 cp --recursive ./build s3://ipa-flashcards-app-frontend

