
image: node:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run-script build
test:
  stage: test
  script:
    - npm test
deploy:
  stage: deploy
  script:
    - npm run-script deploy