image: node:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - installFrontend
  - testFrontend
  - installBackend
  - testBackend
  - buildFrontend
  - deployFrontend
  - deployBackend

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

installFront:
  stage: installFront
  script:
    - cd frontend
    - yarn install

testFront:
  stage: testFront
  script:
    - yarn test
    - cd ..

installBackend:
  stage: installBackend
  script:
    - cd backend
    - npm install

testBackend:
  stage: testBackend
  script:
    - npm test
    - cd ..

buildFrontend:
  stage: buildFrontend
  script:
    - cd frontend
    - yarn build
  only:
    - merge_requests
  artifacts:
    paths:
      - frontend/build
    expire_in: 1 hour

deployFrontend:
  stage: deployFrontend
  image: python:latest
  only:
    - merge_requests
  script:
    - pip install awscli
    - aws s3 cp --recursive ./build s3://ipa-flashcards-app-frontend
    - cd ..

deployBackend:
  stage: deployBackend
  only:
    - merge_requests
  script:
    - cd backend
    - serverless deploy
