
image: node:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - test
  - deploy
cache:
  paths:
    - node_modules

build:
  stage: build
  script:
    - cd frontend
    - yarn install
    - yarn build
test:
  stage: test
  script:
    - yarn test
deploy:
  stage: deploy
  script:
    - yarn deploy