service: ipa-flashcards-app
plugins:
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
  - serverless-mocha-plugin
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  stackName: ipa-flashcards-app-stack-${self:provider.stage}
  apiName: ipa-flashcards-app-${self:provider.stage}
  deploymentBucket:
    name: ipa-flashcards-app-${self:provider.stage}

functions:
  status:
    handler: src/status/index.handler
    events:
      - http:
          path: /status
          method: get
          cors: true




