const INTERNAL_SERVER_ERROR = 500;
const SUCCESSFUL_RESPONSE = 200;
const UNPROCESSABLE_ENTITY = 422;
const BAD_REQUEST = 400;

module.exports = {
    INTERNAL_SERVER_ERROR,
    SUCCESSFUL_RESPONSE,
    UNPROCESSABLE_ENTITY,
    BAD_REQUEST,
};